"""Embedding generation module for the car image RAG pipeline.

Reads the image manifest produced by ``ingest.py``, generates CLIP embeddings
for every image in batches, and persists the resulting embedding matrix
(``image_embeddings.npy``) alongside an aligned metadata JSON file.

Usage (CLI)::

    python -m src.embed --manifest-path embeddings/manifest.json \
                        --embeddings-path embeddings/image_embeddings.npy \
                        --metadata-path embeddings/image_metadata.json \
                        --batch-size 64
"""
from __future__ import annotations
import argparse
from pathlib import Path
import numpy as np
try:  # Supports both `python -m src.embed` and `python src/embed.py`.
    from src.clip_backend import ClipConfig, ClipEncoder
    from src.utils import ensure_dir, load_json, save_json
except ModuleNotFoundError:  # pragma: no cover - script execution fallback
    from clip_backend import ClipConfig, ClipEncoder
    from utils import ensure_dir, load_json, save_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate CLIP embeddings for car images.")
    parser.add_argument(
        "--manifest-path",
        type=Path,
        default=Path("embeddings/manifest.json"),
        help="Path to manifest generated by ingest.py",
    )
    parser.add_argument(
        "--embeddings-path",
        type=Path,
        default=Path("embeddings/image_embeddings.npy"),
        help="Output .npy file for image embeddings.",
    )
    parser.add_argument(
        "--metadata-path",
        type=Path,
        default=Path("embeddings/image_metadata.json"),
        help="Output JSON metadata file aligned with embeddings.",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="ViT-B-32",
        help="OpenCLIP model name.",
    )
    parser.add_argument(
        "--pretrained",
        type=str,
        default="laion2b_s34b_b79k",
        help="OpenCLIP pretrained checkpoint identifier.",
    )
    parser.add_argument("--batch-size", type=int, default=64, help="Image batch size.")
    parser.add_argument(
        "--num-workers",
        type=int,
        default=0,
        help="DataLoader worker count.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default=None,
        help="Torch device (e.g., cuda, cpu). Defaults to auto.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest = load_json(args.manifest_path)
    if not isinstance(manifest, list):
        raise ValueError(f"Manifest at {args.manifest_path} is malformed.")

    image_paths = [Path(row["file_path"]) for row in manifest]
    if not image_paths:
        raise ValueError("No images found in manifest. Run ingest.py first.")

    encoder = ClipEncoder(
        ClipConfig(
            model_name=args.model_name,
            pretrained=args.pretrained,
            device=args.device,
        )
    )
    embeddings, ordered_paths = encoder.encode_images(
        image_paths=image_paths,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        show_progress=True,
    )

    metadata_by_path = {str(Path(row["file_path"]).resolve()): row for row in manifest}
    ordered_metadata = [metadata_by_path[str(Path(path).resolve())] for path in ordered_paths]

    ensure_dir(args.embeddings_path.parent)
    np.save(args.embeddings_path, embeddings.astype(np.float32, copy=False))
    save_json(ordered_metadata, args.metadata_path)

    print(f"Embedding shape: {embeddings.shape}")
    print(f"Embeddings saved to: {args.embeddings_path}")
    print(f"Metadata saved to: {args.metadata_path}")


if __name__ == "__main__":
    main()
